### ISSUE TITLE
hwclock[TIME plugins] failed to execute

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#110]
But it works once my system get started. My guess is that it lacks a `/dev/xxx` before udevd started. Do you have any idea on how to adjust the order?

**Comment by troglobit** [comment]
Hmm, that should not be a problem as long as the kernel is built with `CONFIG_DEVTMPFS`, which is strongly recommended for other purposes as well ... or maybe you don't have a `/dev/rtc0` module loaded?

**Comment by xhebox** [comment]
Confirm. My suggestion is making it a task.

EDIT: btw, i think this should be changed to a run/task too, since udevd may not run at the time.
```
/* Debian has this little script to copy generated rules while the system was read-only */
        if (udev && fexist("/lib/udev/udev-finish"))
                run_interactive("/lib/udev/udev-finish", "Finalizing udev");
```

**Comment by troglobit** [comment]
The hwclock plugin could possibly as a task ... but for my embedded systems I'd really want it to run as soon as possible so kernel + userspace have the correct time.  But I'll look into it.

The udev-finish thing is currently not possible to move to a run/task because the event loop starts too late.  I've been meaning to try to start the event loop much earlier to facilitate relocating parts of the boot process to run/tasklets in the bootstrap runlevel.  It's on the TODO  list ... sorry.

**Comment by xhebox** [comment]
I see, maybe make both methods available at the same time, that's also a good workaround. But yes, redesign to let event loop start really earlier is the best solution. We could even make a more generic system to replace plugin&service system if that's possible, so that tty/plugin in c/service/task or so, could all be controlled by one single system, simple and efficient.
 
It's not a big deal, no matter :).

**Comment by troglobit** [comment]
@abucodonosor Yup, and we should probably add `.conf` support for which `/dev/rtcN` to use (defaulting to `/dev/rtc` obvs.). The system could have several ...

**Comment by troglobit** [comment]
I believe this has been fixed, in two parts:

  * 744fdd6 - adds native support for RTC, skipping external hwclock tool
  * 1c6464a - adds automatic modprobe support to load RTC driver(s)
