### ISSUE TITLE
How fast?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [troglobit/finit#121]
With a name list fast init I'm curious how boot times compare to runit, systemd, and openrc.

I'd also be interested in seeing a detailed comparison between finit and other init systems.

**Comment by troglobit** [comment]
The name is more of an artefact of its ancestry, being re-engineered from the Asus EeePC "fastinit".  I don't maintain any detailed comparison or records of boot times since this invariably differs a lot between systems and work-loads/use-cases.

The contrib/ section holds some pointers on how to get Finit running with different distributions, if you'd like to give it a try yourself.  However, I'm not going to do this myself, so I'll be closing this issue since I don't see metrics as a way forward to promote Finit over other init systems.
