### ISSUE TITLE
Always show all scripts executed from rc.local or runparts

### ISSUE THREAD

**Issue by troglobit** [troglobit/finit#127]
... or at least make it configurable.  Many embedded systems use this feature to extend,
or even live-patch systems between major upgrades of firmware.  Security wise it is a
good thing to at least show on the console what scripts are executed outside the normal
bootstrap path.

**Comment by jackuess** [comment]
@troglobit For `rc.local` I don't think there's much more we can do since execution of the script is handed over to whatever is in the shebang in `rc.local`. All we can do is show on the console that `rc.local` is called, and that's [already implemented](https://github.com/troglobit/finit/blob/10d49641065928ecfd65635a351943b7b3fb9180/src/finit.c#L305).

For the runparts part, i guess some output like this would suffice:

```
[ STATUS ] Calling /rc.d/0001-foo
[ STATUS ] Calling /rc.d/0002-bar
```

**Comment by troglobit** [comment]
Sounds more than reasonable.  Ah, thanks had completely forgotten  about that!  Great, the runparts progress should be fairly straight forward :+1:
