### ISSUE TITLE
Feature request, pass SERVICE_IDENT as env to executing app

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#191]
Is it possible to make SERVICE_IDENT  passed to the executing app as well?

In my case, I've got a wrapper script called "app-wrapper". I want to know the service name that's being executed so I can create an appropriate pid file for this service, especially in the case of multiple services with same bin but different app.

Right now, it's passed to pre & post scripts but not the app itself (or in my case app wrapper script).

My workaround is to make different env files for each service just to contain this, but that's a bit ugly compared to how the pre/post scripts handle it.

**Comment by troglobit** [comment]
First of all, no this is not a bug.  Leaking environment to services or tasks is not usually desirable.  Is this something that other init processes do, like systemd?  If so, please share a link to some information so I can read up.

I don't understand your use-case, why do you need the app-wrapper, why not have a separate script for each service?  It really sounds like you're not working with Finit, rather fighting against it.  But that's judging from your other reports as well, this one I just don't understand.

**Comment by hongkongkiwi** [comment]
In my situation, there are two distinct cases where I am using a wrapper script:
1. I have some services which do not have an option for foreground running nor create a PID. So I have a app-wrapper script which can do this. (see my [gist here](https://gist.github.com/hongkongkiwi/fe310bf4c4d9acddafb8743b0ad02b33) for script). It's generic. Finit has the option to create a pid with `pid:` but it doesn't seem to handle the pid of a service that forks itself (just for example, syslogd without the -n option). In my script, the way I handle this is to use `pidof -s syslogd` to lookup the pid after the process is launched, then I write to a file in my script and use [waitpid](https://github.com/xiezhenye/waitpid) to hold until that pid dies. If the monitored pid dies, then the script will finish, or if the script dies then the monitored pid is sent a term signal, so they are linked together. It's not ideal, but solves this problem pretty well.
If Finit already handles this functionality, then I may have missed it and can dispense with the wrapper script in this use-cacse.

2. The other use case I have is where some services do not work in Finit, but work perfectly fine when run via a script or command line. This is a slight malfunction somehow and I'm not sure whats causing this one, it's a bit hard to debug. I havn't been able to find why this happens in this case, specifically it's **busybox syslogd** & **chronyd**, all other services work fine, but those do not. When running an identical command line manually as root user, they work perfectly. The services themselves also run, but Finit thinks they don't and terminates them.

Both of these cases can be fixed with an app-wrapper script. The app wrapper script would greatly benefit from knowing which service is calling it, incase you use the `name:` option in finit to rename the service so that the pid is appropriately named for that service.

Without passing through a variable like this, the app-wrapper script doesn't know when you rename the service in Finit and you have to manually pass this in via an env file.

**Comment by troglobit** [comment]
Finit has support for traditional System V init scripts, the services these scripts start usually fork to the background.  So the way to run such applications is to use the `sysv` directive instead of `service`.  This way finit will call `foo start` and `foo stop` to stop and start the service, and attempt to find the PID after the fact.  You can also add the `pid:!/path/to/pidfile.pid` to the sysv service.

I haven't tested chronyd, but Finit supports running Alpine Linux systems, which use syslogd.  So I suggest having a look at the contrib section, it has scripts for running BusyBox syslogd in the alpine section.

I'm going to decline this feature request.  I suggest you use a dedicated wrapper script for with a unique name instead, or set up symlinks to a wrapper script and use $0 to check the name instead.  I see no use-case for any of this for us, so supporting it with code and testing would just be extra job we do for us that has no benefit.
