### ISSUE TITLE
/run should be chmod 755 when mounted by finit

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#221]
It appears that finit mounts /run without +rw access for non-root users.

This causes mosquitto (running as mosquitto user) to fail in my case.

It would be good for finit to `chmod 755` (or mount with +rw) for the /run directory so that non-root users can save pid's.

**Comment by troglobit** [comment]
This is by design (security), c.f. SysV init and systemd do the same.  Finit [only mounts /run](https://github.com/troglobit/finit/blob/master/src/finit.c#L301) if it's not already mounted from /etc/fstab -- check here for an example:

https://github.com/westermo/netbox/blob/master/board/common/rootfs/etc/fstab

**Comment by troglobit** [comment]
Closing, user override exists.
