### ISSUE TITLE
Bug in contrib alpine build.sh

### ISSUE THREAD

**Issue by pwFoo** [troglobit/finit#288]
Hi,

there is an error in build contrib alpine finit:
https://github.com/troglobit/finit/blob/master/contrib/alpine/build.sh

Missing `--with-sulogin` flag on line 21 / 22

**Comment by troglobit** [comment]
Wouldn't call it an error, more of an omission or example of how Finit can be compiled for Alpine Linux rather than an absolute.  Alpine ships a native sulogin in the util-linux-login apk.  The bundled sulogin in Finit is disabled by default since most distros ship their own, which usually is more secure anyway.
