### ISSUE TITLE
Add pam support

### ISSUE THREAD

**Issue by liuming50** [troglobit/finit#309]
We are using finit as our init manager, and we found it's seems lack of PAM support?

Is there any plan add PAM support?

**Comment by troglobit** [comment]
Didn't even know PID 1 needed to know about PAM.  Do you have any more information about this, or can explain your requirements?

**Comment by liuming50** [comment]
@troglobit like systemd pam: https://www.freedesktop.org/software/systemd/man/pam_systemd.html?_sm_au_=iHVDqr5ZW1FtkF6NH22GBKHMtcjKq

When start a login console from finit, could the session be controlled under PAM?

**Comment by troglobit** [comment]
Aha, you mean for login.  Well, you can use a getty that supports PAM instead of the default getty shipped with Finit.  For instance, at my old job we used the BusyBox getty (remember to enable PAM support in BusyBox), which worked fine to set up different PAM chains for local/console and remote logins (ssh/telnet).  I've documented it here [TTYs and Consoles](https://github.com/troglobit/finit/blob/master/doc/config.md#ttys-and-consoles).

I considered adding PAM support to the Finit getty, but I've not needed it myself yet.  If someone cares strongly or want to add PAM support themselves, I'm not against it.

**Comment by liuming50** [comment]
@troglobit thanks for the comments, I can try add a tty service with PAM support.

**Comment by troglobit** [comment]
I've looked into this some more now.  From the looks of it you don't need any PAM support in the getty program, only `/bin/login`, which in the case of BusyBox is available.  So I've decided to close this as not-applicable (invalid).
