### ISSUE TITLE
Missing hook for HOOK_NETWORK_DOWN?

### ISSUE THREAD

**Issue by hongkongkiwi** [troglobit/finit#319]
I notice that there is a hook for `HOOK_NETWORK_UP`, however there's no hook for `HOOK_NETWORK_DOWN`

I see that this is actually a step during shutdown
```
[ OK ] Taking down network interfaces ...
```

Just wondering if this was intentional or an accident? I don't need this hook, but just thought I'd check.

**Comment by troglobit** [comment]
This was actually by design, at least initially, before we changed things around so network up/down runs in the background (relying on net/ conditions to synchronize services).

Now that both up and down run in the background I guess we can add an async hook also for `HOOK_NETWORK_DOWN`.  Thanks for bringing it to my attention!
