### ISSUE TITLE
finit crashes if creating inetd service fails

### ISSUE THREAD

**Issue by villains** [troglobit/finit#36]
I was experimenting with having inetd start dropbear when the eth0 interface comes up.

However on my small embedded system, I did not have the usual netbase package files installed. This caused finit to crash during boot and rendered the system unusable.

An ideal solution would be if finit gracefully reported errors if inetd service creation fails, rather than exiting early and preventing the system from starting.

I realize these problems would rarely occur in the majority of cases, but for minimal embedded Linux systems, it may be a concern.

Two cases of interest:

##  (1) Trying to use a named service

First I tried to use ssh by name, forgetting that I had not installed the netbase files in /etc.

finit.conf line:

> inetd ssh/tcp@*,!eth0  nowait [2345] /usr/sbin/dropbear -i -B -R -F -- SSH service

Error messages during boot:

> netd.c:getent() - Invalid/unknown inetd service, cannot create custom entry.finit:/home/markus/gumstix/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/finit/2.4-r0/git/service.c:service_register() - Failed registering new inetd service ssh.[    3.849273] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b

### Result

- Service 'ssh' was not recognized, because file /etc/services is absent
- finit crashes
- System cannot boot

## (2) Trying to use a protocol by name

Next I tried using the port number 22, instead of the named service 'ssh'.

finit.conf line:

> inetd 22/tcp@*,!eth0  nowait [2345] /usr/sbin/dropbear -i -B -R -F -- SSH service

Error messages during boot:

> netd.c:getent() - Cannot find proto tcp, skipping.finit:/home/markus/gumstix/yocto/build/tmp/work/cortexa8hf-vfp-neon-poky-linux-gnueabi/finit/2.4-r0/git/service.c:service_register() - Failed registering new inetd service 22.[    3.835113] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b

### Result

- Gets further but crashes when trying to look up the protocol name 'tcp', because the file /etc/protocols is absent
- System cannot boot

**Comment by villains** [comment]
P.S. I do realize that using "!eth0" in the finit.conf line will prevent dropbear on eth0 :)

**Comment by troglobit** [comment]
Yep, these are really good examples of things I'd like to iron out before the 3.0 release.  Thank you
for summarizing them so well!

First of all, Finit should of course not segfault and exit on such measly little problems. That's just embarrassing ... :flushed: 

I've been pondering if a base version of `/etc/protocols` and `/etc/services` should be kept as built-in, or similar, at least tcp/udp should be recognized. But maybe it's better to just work on the other thing I've been thinking about improving &mdash; early logging and improved fallback handling on critical errors.

Consider for a moment that the above problem with segfaulting is fixed.  For all unknown services, failed mounting, non-writeable rootfs, etc., we need a way of logging this so we can debug it later.  To that end I've been reading up on logging to `/dev/kmsg` before a userspace daemon registers `/dev/log` for the `syslog()` API.  Of course we still need to log critical errors to `stderr` as well, but since there often is no operator present on the console, and/or the console is lost due to massive amounts of output, we need some way to both serialize events and calmly analyze them.  In particular at bringup :wink: 

Next, and I think this is in the TODO, the netlink plugin needs to be extended with support for `IFF_RUNNING` to detect actual link-up.  We have another libnl-based plugin at work that does this, and more, which is awesome!  We haven't included it in the Finit distribution, mostly to not mix up the licensing (libnl is LGPL).

Also, I need to improve the documentation for the inetd syntax.  It's terse and slightly complex, yet beautifully compact.  You seem to have grasped it, though I think more examples are in order :sweat_smile: 

I will start tomorrow to look into the segfaulting issue and then during the weekend try to cook up some initial `/dev/kmsg` prototype.

**Comment by troglobit** [comment]
@villains I hope the recent set of features and fixes come in handy. Thank you for the report!

**Comment by villains** [comment]
Hey @troglobit, my pleasure, and thank YOU very much, I am looking forward to trying out the 3.0 beta in the coming days. All the best!
