### ISSUE TITLE
Suggestion: more choices about the redirection of service

### ISSUE THREAD

**Issue by xhebox** [troglobit/finit#44]
```
task    [2345] log <svc/sbin/syslogd> /sbin/ifup -a                      -- Networking
```

Redirecting to syslog is now the only choice, right?Could not there be more choices , for example `none(/dev/null)` , `/var/log/xx.log(file)`?I ran finit on my own distro, and no supported syslog.I like to keep it simple :D

Could it be added in finit?If not, i will close the issue.Or i can try to make a pull request if you're busy.

**Comment by troglobit** [comment]
Yeah, I've been thinking about this myself. How about the following syntax?

    log:null
    log:level=debug

**Comment by xhebox** [comment]
```
log:null;level=debug
log:/tmp/ss.log;level=normal
```
Like this?

**Comment by troglobit** [comment]
Hmm, yeah possibly. I'm a little bit more in favor of redirecting from
level and facility from the syslog daemon.

Let me sleep on it :)

**Comment by troglobit** [comment]
The `level` is the log level for which messages to stdout/stderr are redirected to syslog with.  Usually the `info` level is used, which can then be filtered out using `/etc/syslog.conf` or `/etc/rsyslog.conf`, or similar.   One could of course redirect `stdout` to syslog using level=debug, and `stderr` using level=err, but in my experience developers that use `printf()`/`fprintf()` instead of a proper logging framework don't care enough to use `stderr` only for errors.

Here's my enhanced proposal, slight variant of yours:

    # Redirect stderr/stdout to syslog, defaults to facility=user,level=info
    service ... log ...
    
    # Redirect stderr/stdout to a log file, facility and level is unused and not applicable
    service ... log:/path/to/logfile ...

    # Redirect stderr/stdout to syslog as LOG_DAEMON and LOG_CRIT
    service ... log:facility=daemon,level=crit ...

With these sub-options to the log command I believe we can cover most cases. Applications writing directly to `/dev/console`, like `udevadm` are however impossble to handle this way. Maybe cgroups could be used to prevent acccess, but then again those applications may crash :-/

Another issue with logging to a file, instead of syslog, is that many embedded systems do not have log rotation, so the (ram)disk used for logging can quickly get full.  Therefore a separate global setting for log rotation may be in order:

    # Max file size for each log file: 100 kiB, rotate out log => log.1 => log.2.gz => log.3.gz => log.4.gz
    log size=100k count=4

Adding this kind of logic to Finit is almost like adding support for a full blown syslog daemon, which may be a good idea ;-)

**Comment by troglobit** [comment]
**Note**: remember log file rotation, when `log:/path/to/logfile` is selected, which is we already do for utmp files.

**Comment by troglobit** [comment]
The following commits implement most of the above ideas, albeit with a slightly modified syntax:
- cbd4cc8
- f253900
- 306bf0f

Syntax:

     log:/path/to/file
     log:prio:facility.level,tag:ident
     log:null
     log

Still missing global support for max log size and number of rotated files, currently hard coded to 200 kB and 5.

**Comment by troglobit** [comment]
Support for global log rotate settings added in 192d3aa, documented in 617ec7c.  

All done, resolving issue! :smiley::+1:

**Comment by xhebox** [comment]
well done :b
