### ISSUE TITLE
getty: reset tty on entry

### ISSUE THREAD

**Issue by wkz** [troglobit/finit#50]
After a successful login, when the spawned process exits, getty should reset the tty settings. Shells might turn off echo or configure some other non-sane behaviour. Subsequent logins might then not echo the username.

**Comment by troglobit** [comment]
Thx for the report!

**Comment by xhebox** [comment]
@troglobit I've found your builtin tty will broken apps, such as wine. I guess it's related to this issue. 

This is the workaround patch, as you can see, SEGV_BLOCK is passed to the child process of the init. But, after manually excuting /bin/login again, it was cleared. **Maybe other init's setting is passed to the child process.**
```
--- .src/finit-master/sig.c	2016-11-26 15:00:27.519476035 +0000
+++ finit-master/sig.c	2016-11-26 15:00:27.519476035 +0000
@@ -394,7 +394,6 @@
 	uev_signal_init(ctx, &sigchld_watcher, sigchld_cb, NULL, SIGCHLD);
 
 	/* Trap SIGSEGV in case service callbacks crash */
-	uev_signal_init(ctx, &sigsegv_watcher, sigsegv_cb, NULL, SIGSEGV);
 
 	/* Stopping init is a bit tricky. */
 	uev_signal_init(ctx, &sigstop_watcher, sigstop_cb, NULL, SIGSTOP);
```
Also, there's a error which may caused by this:
```
[xhe@xhe-PC ~]$ LANG=C sudo login  xhe
Password: 
[xhe@xhe-PC ~]$ exit
logout
Segmentation fault
```

Hope you can find a way to solve this quickly or get the non-builtin tty back? This is the last wall to stop me getting wine worked with musl :D. I could run the most famous chat programs with wine soon.
[Details about the found of issue](https://github.com/xhebox/noname-linux/issues/2#issuecomment-263061951)
