### ISSUE TITLE
Make a pidfile if program does not

### ISSUE THREAD

**Issue by joerg-krause** [troglobit/finit#95]
Some programs do not create a pidfile. Using `start-stop-daemon -m` in an SysV-init based system makes a pidfile for those programs. Finit does not have this feature, right? Would it be possible to add the functionality?

**Comment by troglobit** [comment]
Well, then I'd say it was problem that primarily should be fixed with that program ;)

Joking aside, no Finit does not have this feature (anymore). It monitors the PID of the process by requiring it runs in the foreground. The existence of a PID file is monitored to generate conditions that can be used to trigger the start of other services, or even restart these dependant services should the PID file be updated (which a service should do to acknowledge a SIGHUP to reload its .conf file, for instance).

Adding support for creating PID files for programs that don't themselves is quite simple.  My only conundrum is what the syntax should be?  As you may have noticed I'm a big fan of keeping everything on one line with av very compact (yet hopefully readable) syntax.

In #44 we have proposal to enhance the `log` keyword, maybe we could do something similar? 

```
# Create PID file using basename(3) of service
service ... pid ...

# Create PID file using the provided absolute filename
service ... pid:/path/to/pidfile ...

# Create PID file in _PATH_VARRUN, i.e. /run/pidfile
service ... pid:pidfile ...
```

**Comment by joerg-krause** [comment]
Using the pidfile as condition for starting other services is exactly the use case I'm trying to do. Unfortunately, some programs only create a pidfile if started in background mode, others never :-(

I'm fine with the proposal regarding the syntax. The main thing is that it's documented. (I am quite happy about that Finit is well documented).

**Comment by troglobit** [comment]
Uh, not creating a PID file just because it's running in the foreground is ... evil. Here's to hoping the widespread use of systemd will help mitigate those trainwrecks.

OK, I'll look into it in a day or two so we can get it into v3.1.  (Thank you, I'm sure the docs can be much improved upon, but I'm glad it's of help already! :-)

**Comment by joerg-krause** [comment]
Thanks, that would be great!

**Comment by troglobit** [comment]
Sorry for taking so long, got held up by another project.  Hopefully 6a6ae6f does what you wanted.  I haven't had time to document it yet, but I will, promise :-)

**Comment by joerg-krause** [comment]
Many thanks for adding this feature! Great work! Unfortunately, I'm stuck with another project right now, but I hope I am able to test the new rc2 soon.

**Comment by troglobit** [comment]
No problem mate, it was a really good suggestion that lined up well with my own projects ☺️

Just FYI, I'll likely release v3.1 within a week.
